### ISSUE TITLE
Install Fails - What what are prerequisites?

### ISSUE THREAD

**Issue by rgeleta** [jmcelroy5/SF-in-Progress#20]
Per readme.md
1. cloned project 
2. changed directory to SF-in-Progress
3. typed "npm install"

Results expected
npm libraries installed

Actual results
npm: command not found

Environments tested
Windows XP 
Windows 8.1
OS X 10.9.5
CentOS 6.6

**Comment by mcastillon** [comment]
A similar error happened to me. What worked for me was running 'npm install' in the node.js command prompt as opposed to git bash. Hope that helps!

**Comment by kruppel** [comment]
@rgeleta Sounds like you need node installed (npm is installed with node). DigitalOcean has at a couple of articles on the topic:
1. [How to install Node.js on a Centos 7 server](https://www.digitalocean.com/community/tutorials/how-to-install-node-js-on-a-centos-7-server)
2. [How To Install Node.js with NVM (Node Version Manager) on a VPS](https://www.digitalocean.com/community/tutorials/how-to-install-node-js-with-nvm-node-version-manager-on-a-vps)

I personally prefer the package manager approach, but use [tj/n](https://github.com/tj/n) over [creationix/nvm](https://github.com/creationix/nvm). To each their own, though.

**Comment by rgeleta** [comment]
@kruppel - Thank you, your observation was correct and the information you provided led me to what I needed to get started on my first platform.  

Since I'm new to node, now I need to learn how to decipher the warning/error messages that resulted from the "npm install" process and determine if the problems reported affect running the software. 

In the meantime, picking up from where I left off, I did
cd www
npm start
and got some great output worthy of additional research
Per on-screen instructions, here is contents of npm-debug.log

<pre>
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'start' ]
2 info using npm@2.7.4
3 info using node@v0.12.2
4 verbose node symlink C:\Program Files\nodejs\\node.exe
5 verbose run-script [ 'prestart', 'start', 'poststart' ]
6 info prestart sf-in-progress@0.0.0
7 info start sf-in-progress@0.0.0
8 verbose unsafe-perm in lifecycle true
9 info sf-in-progress@0.0.0 Failed to exec start script
10 verbose stack Error: sf-in-progress@0.0.0 start: `node server.js`
10 verbose stack Exit status 1
10 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\lifecycle.js:213:16)
10 verbose stack     at EventEmitter.emit (events.js:110:17)
10 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\spawn.js:14:12)
10 verbose stack     at ChildProcess.emit (events.js:110:17)
10 verbose stack     at maybeClose (child_process.js:1015:16)
10 verbose stack     at Process.ChildProcess._handle.onexit (child_process.js:1087:5)
11 verbose pkgid sf-in-progress@0.0.0
12 verbose cwd C:\_Client_Files\sfip\SF-in-Progress\www
13 error Windows_NT 5.1.2600
14 error argv "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "start"
15 error node v0.12.2
16 error npm  v2.7.4
17 error code ELIFECYCLE
18 error sf-in-progress@0.0.0 start: `node server.js`
18 error Exit status 1
19 error Failed at the sf-in-progress@0.0.0 start script 'node server.js'.
19 error This is most likely a problem with the sf-in-progress package,
19 error not with npm itself.
19 error Tell the author that this fails on your system:
19 error     node server.js
19 error You can get their info via:
19 error     npm owner ls sf-in-progress
19 error There is likely additional logging output above.
20 verbose exit [ 1, true ]
</pre>

If it would be more helpful to start a new issue, let me know.

Thanks again

**Comment by kruppel** [comment]
@rgeleta If I had to guess, I'd say it's because the [npm script uses "/" as a delimiter](https://github.com/jmcelroy5/SF-in-Progress/blob/cf8cd7752d50dc8be9f0cea15dcd43b7169757fb/package.json#L24), which runs well on *nix systems, [not so much on Windows](https://gist.github.com/domenic/2790533#being-windows-developer-friendly).

Try `npm run hoodie-server start` and see what happens.

**Comment by rgeleta** [comment]
@kruppel 
<code>npm run hoodie-server start</code>
gives it a good go, but hoodie-server script is missing.

Here is new npm-debug.log contents

<pre>
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'hoodie-server',
1 verbose cli   'start' ]
2 info using npm@2.7.4
3 info using node@v0.12.2
4 verbose node symlink C:\Program Files\nodejs\\node.exe
5 verbose stack Error: missing script: hoodie-server
5 verbose stack     at run (C:\Program Files\nodejs\node_modules\npm\lib\run-script.js:165:19)
5 verbose stack     at C:\Program Files\nodejs\node_modules\npm\lib\run-script.js:81:5
5 verbose stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\read-package-json\read-json.js:52:40
5 verbose stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\read-package-json\read-json.js:376:33
5 verbose stack     at checkBinReferences_ (C:\Program Files\nodejs\node_modules\npm\node_modules\read-package-json\read-json.js:341:59)
5 verbose stack     at final (C:\Program Files\nodejs\node_modules\npm\node_modules\read-package-json\read-json.js:373:17)
5 verbose stack     at then (C:\Program Files\nodejs\node_modules\npm\node_modules\read-package-json\read-json.js:127:33)
5 verbose stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\read-package-json\read-json.js:189:48
5 verbose stack     at evalmachine.<anonymous>:263:20
5 verbose stack     at OpenReq.Req.done (C:\Program Files\nodejs\node_modules\npm\node_modules\graceful-fs\graceful-fs.js:141:5)
6 verbose cwd C:\_Client_Files\sfip\SF-in-Progress
7 error Windows_NT 5.1.2600
8 error argv "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "hoodie-server" "start"
9 error node v0.12.2
10 error npm  v2.7.4
11 error missing script: hoodie-server
12 error If you need help, you may report this error at:
12 error     &lt;https://github.com/npm/npm/issues&gt;
13 verbose exit [ 1, true ]
</pre>
